name: stream-monitor
base: core18
version: git
summary: Monitor your web streams
description: |
  Stream Monitor will continuously monitor any number of web streams for
  problems. It will email you if it detects silence, constant noise, or
  similar issues.

grade: stable
confinement: strict

apps:
  stream-monitor:
    command: bin/stream-monitor
    plugs: [network]

  daemon:
    command: bin/stream-monitor -c $SNAP_DATA/stream-monitor.conf
    daemon: simple
    restart-condition: always
    plugs: [network]

parts:
  stream-monitor:
    plugin: python
    source: .
    requirements: [requirements.txt]
    after: [aubio]

  # Can't seem to be able to install this from pip for some reason
  aubio:
    plugin: python
    source: https://github.com/aubio/aubio.git
    source-branch: 0.4.9
    source-depth: 1
    requirements: [requirements.txt]
    build-packages:
      - libavresample-dev
      - libavformat-dev
      - libswresample-dev
      - libavutil-dev
      - libavcodec-dev
      - pkg-config

    stage-packages:
      - libavresample3
      - libavutil55
      - libavformat57
      - libavcodec57
      - libswresample2